export type DomainErrorCode =
  | "STALE_VERSION"
  | "INVALID_TRANSITION"
  | "REPLY_NOT_ALLOWED"
  | "INVALID_ATTESTATION_CONTROL"
  | "INVALID_MESSAGE_BODY"
  | "INVALID_ROUTING_CATEGORY"
  | "INVALID_QUEUE_CONFIGURATION"
  | "INVALID_ATTACHMENT_POLICY"
  | "INVALID_ATTACHMENT_METADATA"
  | "INVALID_ATTACHMENT_STATE"
  | "INVALID_SCAN_RESULT"
  | "ATTACHMENT_COUNT_LIMIT_EXCEEDED"
  | "STALE_ATTACHMENT_POLICY"
  | "INVALID_ACCESS_GRANT"
  | "INVALID_ACCESS_GRANT_POLICY"
  | "ACCESS_GRANT_THREAD_NOT_ELIGIBLE"
  | "ACCESS_GRANT_AUTHORITY_CHANGED";

export class DomainError extends Error {
  constructor(
    public readonly code: DomainErrorCode,
    message: string,
  ) {
    super(message);
    this.name = "DomainError";
  }
}
